joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.02
    autorepeat_rate: 20.0 # milliseconds

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.26 #0.002   
      
    axis_angular:
      yaw: 0 
    scale_angular:
      yaw: 1.6 #0.02
    
    enable_button: 1
    enable_turbo_button: 0 

    require_enable_button: true
